"""``ghostc-agent`` — the client-side agent workflow CLI.

    ghostc-agent run-task --task <file|-> [--backend auto|claude|stub]
    ghostc-agent print-graph            # regenerate client_agent/graph.md

Split from ``ghostc`` proper: ``ghostc`` is the deterministic privacy compiler,
``ghostc-agent`` is the LangGraph orchestrator on top of it (needs the [agents] extra).
"""
from __future__ import annotations

import hashlib
from pathlib import Path

import click

from ghostc.config import ConfigError, load_config


@click.group()
def main() -> None:
    """Client-side agent: real task -> ghost branch + TASK.md -> ghost PR -> real-repo PR."""


@main.command("run-task")
@click.option("--task", "task_path", required=True, type=click.Path(),
              help="Real implementation task text: a file path, or '-' for stdin.")
@click.option("--task-id", default=None,
              help="Stable id for the ghost/real branches + PRs (default: derived).")
@click.option("--real-repo", default="workspace/real", show_default=True, type=click.Path())
@click.option("--ghost-tree", default="workspace/ghost", show_default=True,
              type=click.Path(), help="Ghost repo produced by `ghostc compile`.")
@click.option("--config", "config_path", default="privacy.yaml", show_default=True,
              type=click.Path())
@click.option("--mapping", "mapping_path", default="workspace/private/mapping.json",
              show_default=True, type=click.Path())
@click.option("--audit", "audit_path", default="workspace/private/audit.jsonl",
              show_default=True, type=click.Path())
@click.option("--workspace", default="workspace/agent", show_default=True,
              type=click.Path(), help="Where the agent's ghost/real git remotes live.")
@click.option("--backend", type=click.Choice(["auto", "claude", "stub"]),
              default="auto", show_default=True,
              help="LLM backend for the consistency gate. auto: Claude if a key is set.")
def run_task_cmd(task_path: str, task_id: str | None, real_repo: str, ghost_tree: str,
                 config_path: str, mapping_path: str, audit_path: str, workspace: str,
                 backend: str) -> None:
    """Run one task: real task -> ghost branch + TASK.md -> ghost PR -> reverse-patch ->
    real-repo PR (human review). Fail closed."""
    try:
        from client_agent.graph import run_task
    except ImportError as exc:
        raise SystemExit("the agent workflow needs the [agents] extra:\n"
                         f"  pip install -e '.[agents]'\n  ({exc})")

    try:
        load_config(config_path)
    except ConfigError as exc:
        raise SystemExit(f"INVALID CONFIG\n{exc}")

    text = (click.get_text_stream("stdin").read() if task_path == "-"
            else Path(task_path).read_text(encoding="utf-8"))
    tid = task_id or "task-" + hashlib.sha1(text.encode("utf-8")).hexdigest()[:8]

    state = run_task(text, task_id=tid, real_repo=real_repo, ghost_tree=ghost_tree,
                     config_path=config_path, mapping_path=mapping_path,
                     audit_path=audit_path, workspace=workspace, backend=backend)

    m = state.get("metrics", {})
    if state.get("rejected"):
        click.echo(f"REJECTED (fail closed): {state['rejected']}")
        click.echo(f"  wall-clock: {m.get('wall_clock_s')}s  (metrics + audit still written)")
        raise SystemExit(1)

    rp = state["real_pr"]
    click.echo(f"real PR opened: #{rp['id']}  {rp['ref']}  (branch {rp['branch']})")
    click.echo(f"  ghost PR:     #{state['ghost_pr']['id']}")
    click.echo(f"  consistency:  {m.get('consistency')}  {m.get('consistency_flags') or ''}")
    click.echo(f"  entities:     resolved={m.get('entities_resolved') or []}  "
               f"lossy={m.get('lossy_entities') or []}")
    click.echo(f"  llm:          {m.get('llm_model')}  {m.get('llm_tokens')} tok")
    click.echo(f"  wall-clock:   {m.get('wall_clock_s')}s")
    click.echo("  -> HUMAN REVIEW REQUIRED before merge")


@main.command("print-graph")
@click.option("--out", default="client_agent/graph.md", show_default=True,
              type=click.Path(), help="Write a mermaid diagram of the StateGraph here.")
def print_graph(out: str) -> None:
    """Regenerate the mermaid diagram of the client StateGraph."""
    try:
        from client_agent.graph import graph_mermaid
    except ImportError as exc:
        raise SystemExit(f"needs the [agents] extra: pip install -e '.[agents]'  ({exc})")

    body = graph_mermaid()
    Path(out).write_text(
        "# Client agent — LangGraph\n\n"
        "Auto-generated by `ghostc-agent print-graph`. Topology in "
        "`client_agent/graph.py::_wire`.\n\n"
        f"```mermaid\n{body}\n```\n", encoding="utf-8")
    click.echo(f"wrote {out}")


if __name__ == "__main__":
    main()
