"""Assemble the two pull-request bodies the CI workflow opens for a judge.

``scripts/ci/publish-prs.sh`` runs the verified reduced flow (``client-agent
start`` + ``client-agent open-real-pr``), then calls this module to turn the
per-run rows in ``metrics/agent-runs.jsonl`` into:

* the **ghost task PR** on ``…/ghostc-demo-ghost`` — the sanitized branch the
  consultancy side saw;
* the **reverse-compiled real PR** on ``…/ghostc-demo-real`` — the same work
  translated back through the mapping store, flagged for human review.

Pure stdlib on purpose: the shell wrapper needs it without the ``[agents]`` extra,
and the body assembly is unit-tested (``tests/test_ci_publish.py``) with no
network and no ``gh``.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_FIELDS = ("task_id", "ghost_branch", "real_branch", "base")


def load_rows(metrics_file: str | Path) -> list[dict]:
    p = Path(metrics_file)
    if not p.exists():
        return []
    return [json.loads(ln) for ln in p.read_text(encoding="utf-8").splitlines() if ln.strip()]


def latest(rows: list[dict], **match) -> dict:
    """Newest row (by ``ts``) matching every ``key=value`` in *match*, or ``{}``."""
    hits = [r for r in rows if all(r.get(k) == v for k, v in match.items())]
    return max(hits, key=lambda r: r.get("ts", ""), default={})


def resolve(rows: list[dict], field: str) -> str:
    """One value the publish script needs to name a branch / PR base."""
    if field not in _FIELDS:
        raise SystemExit(f"unknown field {field!r} (want one of {', '.join(_FIELDS)})")
    rev = latest(rows, role="client", command="open-real-pr", outcome="ok")
    start = latest(rows, role="client", command="start")
    if field == "task_id":
        return rev.get("task_id") or start.get("task_id") or ""
    if field == "ghost_branch":
        return (rev.get("ghost_branch") or start.get("ghost_branch")
                or f"ghostc/task/{resolve(rows, 'task_id')}")
    if field == "real_branch":
        return rev.get("real_branch", "")
    return rev.get("base") or "main"


def _fmt_checks(row: dict) -> str:
    t, b = row.get("ghost_tests"), row.get("ghost_build")
    if not t and not b:
        return "n/a (deterministic stub backend)"
    parts = []
    if t:
        parts.append(f"tests {'pass' if t.get('ok') else 'FAIL'} "
                     f"({t.get('pass')}/{t.get('tests')})")
    if b:
        parts.append(f"build {'pass' if b.get('ok') else 'FAIL'}")
    return ", ".join(parts)


def _lst(v) -> str:
    return ", ".join(f"`{x}`" for x in v) if v else "none"


def title(rows: list[dict], side: str) -> str:
    tid = resolve(rows, "task_id") or "task"
    if side == "ghost":
        return f"[ghost] {tid} — sanitized task branch"
    real = resolve(rows, "real_branch").rsplit("/", 1)[-1] or tid
    return f"[real] {real} — reverse-compiled from ghost"


def ghost_body(rows: list[dict]) -> str:
    start = latest(rows, role="client", command="start")
    cons = latest(rows, role="consultancy", command="start")
    tid = resolve(rows, "task_id")
    authors = ", ".join(start.get("consultancy_authors") or []) or "the consultancy agent"
    return "\n".join([
        f"## Ghost task PR — `{tid}`",
        "",
        "Opened by the ghostc client agent. The external consultancy side sees "
        "**only this sanitized branch** — no real client / vendor / internal-service "
        "name crossed the trust boundary. The same work, translated back through the "
        "mapping store, is opened as a separate PR on the **real** demo repo.",
        "",
        "| | |",
        "|---|---|",
        f"| Task branch | `{resolve(rows, 'ghost_branch')}` |",
        f"| Sanitized substitutions | {start.get('substitutions', '?')} entity spellings |",
        f"| Consultancy backend | `{cons.get('backend', '?')}` |",
        f"| Consultancy commits | {start.get('consultancy_commits', '?')} by {authors} |",
        f"| Files changed (ghost) | {cons.get('files_changed', '?')} |",
        f"| Ghost tests / build | {_fmt_checks(cons)} |",
        "",
        "_Generated by `scripts/ci/publish-prs.sh` from `metrics/agent-runs.jsonl`._",
    ]) + "\n"


def real_body(rows: list[dict]) -> str:
    rev = latest(rows, role="client", command="open-real-pr", outcome="ok")
    tid = resolve(rows, "task_id")
    head = [
        f"## Reverse-compiled real PR — `{tid}`",
        "",
        "The consultancy implemented this on the **ghost** repo only. `client-agent "
        "open-real-pr` reverse-compiled that branch through the mapping store onto "
        "this real branch; the on-branch `PR_BODY.md` has the same summary.",
        "",
    ]
    return "\n".join(head + [
        "| | |",
        "|---|---|",
        f"| Reverse-compiled from | `{rev.get('ghost_branch', '?')}` @ "
        f"`{(rev.get('ghost_handoff') or '')[:10]}` |",
        f"| Real branch | `{rev.get('real_branch', '?')}` |",
        f"| Entities restored | {_lst(rev.get('entities_resolved'))} |",
        f"| Lossy (prose casing) | {_lst(rev.get('lossy_entities'))} |",
        f"| Line-map fallbacks | {_lst(rev.get('fallbacks'))} |",
        f"| Translated | {rev.get('files', '?')} file(s), {rev.get('hunks', '?')} hunk(s) |",
        "",
        "**HUMAN REVIEW REQUIRED** before merge — verify the diff matches the "
        "original ticket and introduces no new real-world entity.",
        "",
        "_Generated by `scripts/ci/publish-prs.sh`._",
    ]) + "\n"


def _main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="python -m client_agent.publish")
    ap.add_argument("action", choices=["resolve", "title", "body"])
    ap.add_argument("--metrics-file", required=True)
    ap.add_argument("--field", choices=_FIELDS)
    ap.add_argument("--side", choices=["ghost", "real"])
    a = ap.parse_args(argv)
    rows = load_rows(a.metrics_file)
    if not rows:
        print(f"no metrics rows in {a.metrics_file}", file=sys.stderr)
        return 2

    if a.action == "resolve":
        if not a.field:
            ap.error("resolve needs --field")
        print(resolve(rows, a.field))
    elif a.action == "title":
        if not a.side:
            ap.error("title needs --side")
        print(title(rows, a.side))
    else:
        if not a.side:
            ap.error("body needs --side")
        print((ghost_body if a.side == "ghost" else real_body)(rows), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
